In [1]:
import pandas as pd
import numpy as np

In [2]:
edo = pd.read_csv(r'C:\KGR5\edogawa_kaneda.csv', encoding = 'cp932')

In [3]:
edo[0:10]

,地区,クラスタ,自転車盗数,大学・短大（NAVITIME）,駅（NAVITIME）,工場,0～4歳,5～9歳,10～14歳,15～19歳,...,民営の借家世帯数,給与住宅世帯数,間借り世帯数,一戸建世帯数,長屋建世帯数,共同住宅世帯数,１・２階建,３～５階建,６～10階建,11階建以上
0,東小松川,0,32,0,0,0,517,498,491,555,...,1959,120,57,2241,44,2617,720,1246,443,208
1,西小松川町,0,3,0,0,0,102,116,152,199,...,370,23,22,727,14,552,194,190,70,98
2,小松川,0,40,0,0,0,707,869,907,947,...,485,118,45,328,25,6175,90,449,407,5229
3,西葛西,1,172,0,1,0,1997,1909,1858,2246,...,9150,773,239,1411,35,18833,1223,3803,6832,6975
4,中葛西,1,137,0,1,0,1771,1532,1405,1870,...,12701,1125,259,2609,93,17752,3243,6430,5294,2785
5,北葛西,0,42,0,0,0,953,1020,954,1033,...,2809,425,74,2414,55,5835,1415,1285,1687,1448
6,南葛西,1,113,0,0,0,1868,1723,1824,1947,...,6351,617,142,1696,94,12460,1279,2875,4732,3574
7,東葛西,1,170,0,0,0,1954,1706,1804,2308,...,13411,1205,309,3908,119,17809,4679,5838,5176,2116
8,新堀,0,9,0,0,0,218,313,297,269,...,647,12,16,737,8,989,321,327,264,77
9,清新町,0,43,0,0,0,519,697,643,710,...,303,90,28,38,21,5472,1,830,820,3821

In [4]:
edo_tmp = edo.drop(['地区', 'クラスタ'], axis=1)
#edo_tmp = edo_tmp.drop('Unnamed: 8', axis=1)
edo_tmp[0:10]

,自転車盗数,大学・短大（NAVITIME）,駅（NAVITIME）,工場,0～4歳,5～9歳,10～14歳,15～19歳,20～24歳,25～29歳,...,民営の借家世帯数,給与住宅世帯数,間借り世帯数,一戸建世帯数,長屋建世帯数,共同住宅世帯数,１・２階建,３～５階建,６～10階建,11階建以上
0,32,0,0,0,517,498,491,555,613,711,...,1959,120,57,2241,44,2617,720,1246,443,208
1,3,0,0,0,102,116,152,199,182,172,...,370,23,22,727,14,552,194,190,70,98
2,40,0,0,0,707,869,907,947,785,675,...,485,118,45,328,25,6175,90,449,407,5229
3,172,0,1,0,1997,1909,1858,2246,2825,3091,...,9150,773,239,1411,35,18833,1223,3803,6832,6975
4,137,0,1,0,1771,1532,1405,1870,3106,3519,...,12701,1125,259,2609,93,17752,3243,6430,5294,2785
5,42,0,0,0,953,1020,954,1033,951,1036,...,2809,425,74,2414,55,5835,1415,1285,1687,1448
6,113,0,0,0,1868,1723,1824,1947,2198,2230,...,6351,617,142,1696,94,12460,1279,2875,4732,3574
7,170,0,0,0,1954,1706,1804,2308,3376,3917,...,13411,1205,309,3908,119,17809,4679,5838,5176,2116
8,9,0,0,0,218,313,297,269,253,209,...,647,12,16,737,8,989,321,327,264,77
9,43,0,0,0,519,697,643,710,635,687,...,303,90,28,38,21,5472,1,830,820,3821

In [5]:
np_edo = edo_tmp.values

In [6]:
np_edo[0:10]

array([[3.20000000e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.17000000e+02, 4.98000000e+02, 4.91000000e+02, 5.55000000e+02,
        6.13000000e+02, 7.11000000e+02, 7.31000000e+02, 8.78000000e+02,
        9.51000000e+02, 8.11000000e+02, 6.93000000e+02, 6.13000000e+02,
        5.47000000e+02, 6.57000000e+02, 6.00000000e+02, 5.44000000e+02,
        4.46364357e+01, 2.24000000e+02, 1.97500000e+03, 1.16700000e+03,
        8.36000000e+02, 7.09000000e+02, 2.17000000e+02, 3.90000000e+01,
        1.40000000e+01, 3.60000000e+01, 3.40000000e+01, 2.64200000e+03,
        1.97500000e+03, 5.76000000e+02, 4.96100000e+03, 9.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 3.74000000e+02, 6.36000000e+02,
        1.20000000e+01, 2.91000000e+02, 3.46000000e+02, 7.08000000e+02,
        1.24000000e+02, 1.76000000e+02, 1.39000000e+02, 2.60000000e+02,
        2.02000000e+02, 1.47000000e+02, 4.18000000e+02, 2.10000000e+01,
        4.07000000e+02, 1.31000000e+02, 5.60000000e+02, 2.93300000e+03,
        1.10900000e+03, 4.76000000e+02, 2.68000000e+03, 8.90000000e+01,
        1.95900000e+03, 1.20000000e+02, 5.70000000e+01, 2.24100000e+03,
        4.40000000e+01, 2.61700000e+03, 7.20000000e+02, 1.24600000e+03,
        4.43000000e+02, 2.08000000e+02],
       [3.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.02000000e+02, 1.16000000e+02, 1.52000000e+02, 1.99000000e+02,
        1.82000000e+02, 1.72000000e+02, 1.76000000e+02, 1.70000000e+02,
        2.83000000e+02, 2.45000000e+02, 2.09000000e+02, 1.82000000e+02,
        1.78000000e+02, 2.06000000e+02, 2.13000000e+02, 1.57000000e+02,
        4.56941380e+01, 4.10000000e+01, 4.67000000e+02, 3.71000000e+02,
        2.37000000e+02, 1.89000000e+02, 6.90000000e+01, 1.60000000e+01,
        9.00000000e+00, 1.40000000e+01, 5.70000000e+01, 7.77000000e+02,
        4.67000000e+02, 1.78000000e+02, 1.40100000e+03, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.25000000e+02, 1.76000000e+02,
        3.00000000e+00, 4.20000000e+01, 1.13000000e+02, 2.40000000e+02,
        1.30000000e+01, 2.80000000e+01, 2.40000000e+01, 9.10000000e+01,
        6.90000000e+01, 2.50000000e+01, 1.14000000e+02, 8.00000000e+00,
        1.17000000e+02, 8.80000000e+01, 1.24000000e+02, 8.92000000e+02,
        3.00000000e+02, 1.71000000e+02, 8.78000000e+02, 0.00000000e+00,
        3.70000000e+02, 2.30000000e+01, 2.20000000e+01, 7.27000000e+02,
        1.40000000e+01, 5.52000000e+02, 1.94000000e+02, 1.90000000e+02,
        7.00000000e+01, 9.80000000e+01],
       [4.00000000e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        7.07000000e+02, 8.69000000e+02, 9.07000000e+02, 9.47000000e+02,
        7.85000000e+02, 6.75000000e+02, 8.20000000e+02, 1.14000000e+03,
        1.50300000e+03, 1.42300000e+03, 1.24100000e+03, 9.80000000e+02,
        8.87000000e+02, 9.47000000e+02, 7.70000000e+02, 6.73000000e+02,
        4.30879145e+01, 1.44600000e+03, 1.75000000e+03, 1.91900000e+03,
        1.35300000e+03, 1.18000000e+03, 2.97000000e+02, 3.60000000e+01,
        1.50000000e+01, 3.20000000e+01, 2.00000000e+00, 4.44200000e+03,
        1.75000000e+03, 8.03000000e+02, 7.03700000e+03, 6.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 3.63000000e+02, 8.09000000e+02,
        2.70000000e+01, 5.74000000e+02, 3.96000000e+02, 1.11300000e+03,
        2.93000000e+02, 1.82000000e+02, 3.45000000e+02, 4.56000000e+02,
        2.26000000e+02, 2.51000000e+02, 5.36000000e+02, 1.80000000e+01,
        5.81000000e+02, 1.55000000e+02, 7.04000000e+02, 4.30200000e+03,
        1.71000000e+03, 9.35000000e+02, 2.66500000e+03, 3.21900000e+03,
        4.85000000e+02, 1.18000000e+02, 4.50000000e+01, 3.28000000e+02,
        2.50000000e+01, 6.17500000e+03, 9.00000000e+01, 4.49000000e+02,
        4.07000000e+02, 5.22900000e+03],
       [1.72000000e+02, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.99700000e+03, 1.90900000e+03, 1.85800000e+03, 2.24600000e+03,
        2.82500000e+03, 3.09100000e+03, 3.48700000e+03, 3.51600000e+03,
        3.86300000e+03, 3.71500000e+03, 2.97900000e+03, 2.25200000e+03,
        2.26500000e+03, 2.49200000e+03, 1.74100000e+03, 1.28900000e+03,
        4.10660211e+01, 2.86300000e+03, 9.67500000e+03, 4.94100000e+03,
        3.40300000e+03, 2.60700000e+03, 5.28000000e+02, 7.30000000e+01,
        1.90000000e+01, 2.27000000e+02, 8.87000000e+02, 1.06740000e+04,
        9.67500000e+03, 1.69500000e+03, 1.93240000e+04, 1.20000000e+01,
        2.00000000e+00, 4.00000000e+00, 9.86000000e+02, 1.60300000e+03,
        3.70000000e+01, 1.88900000e+03, 1.24200000e+03, 2.84700000e+03,
        1.07100000e+03, 6.74000000e+02, 8.93000000e+02, 1.16100000e+03,
        6.10000000e+02, 5.91000000e+02, 1.23100000e+03, 3.10000000e+01,
        1.58100000e+03, 3.12000000e+02, 2.54700000e+03, 9.48000000e+03,
        4.10300000e+03, 2.13600000e+03, 7.14500000e+03, 2.98300000e+03,
        9.15000000e+03, 7.73000000e+02, 2.39000000e+02, 1.41100000e+03,
        3.50000000e+01, 1.88330000e+04, 1.22300000e+03, 3.80300000e+03,
        6.83200000e+03, 6.97500000e+03],
       [1.37000000e+02, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.77100000e+03, 1.53200000e+03, 1.40500000e+03, 1.87000000e+03,
        3.10600000e+03, 3.51900000e+03, 3.51600000e+03, 3.51900000e+03,
        3.63800000e+03, 3.19400000e+03, 2.54000000e+03, 1.73100000e+03,
        1.74800000e+03, 1.76900000e+03, 1.35400000e+03, 9.85000000e+02,
        3.95378507e+01, 1.87000000e+03, 1.18190000e+04, 4.04500000e+03,
        2.59900000e+03, 1.95800000e+03, 4.38000000e+02, 9.40000000e+01,
        2.60000000e+01, 2.28000000e+02, 4.40000000e+02, 8.31500000e+03,
        1.18190000e+04, 1.46000000e+03, 1.70440000e+04, 1.10000000e+01,
        1.00000000e+00, 3.00000000e+00, 1.02000000e+03, 1.36400000e+03,
        3.00000000e+01, 1.43900000e+03, 1.32900000e+03, 2.47100000e+03,
        7.53000000e+02, 6.35000000e+02, 7.61000000e+02, 1.07500000e+03,
        5.87000000e+02, 4.59000000e+02, 1.00500000e+03, 3.00000000e+01,
        1.22600000e+03, 2.49000000e+02, 2.59600000e+03, 7.46700000e+03,
        3.09100000e+03, 1.84600000e+03, 6.18100000e+03, 2.06000000e+02,
        1.27010000e+04, 1.12500000e+03, 2.59000000e+02, 2.60900000e+03,
        9.30000000e+01, 1.77520000e+04, 3.24300000e+03, 6.43000000e+03,
        5.29400000e+03, 2.78500000e+03],
       [4.20000000e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        9.53000000e+02, 1.02000000e+03, 9.54000000e+02, 1.03300000e+03,
        9.51000000e+02, 1.03600000e+03, 1.21500000e+03, 1.49200000e+03,
        1.83400000e+03, 1.69700000e+03, 1.34700000e+03, 9.43000000e+02,
        1.05600000e+03, 1.24700000e+03, 1.13100000e+03, 8.03000000e+02,
        4.29476132e+01, 5.16000000e+02, 2.88800000e+03, 2.15900000e+03,
        1.63900000e+03, 1.35200000e+03, 3.30000000e+02, 5.30000000e+01,
        1.40000000e+01, 5.20000000e+01, 9.60000000e+01, 5.12200000e+03,
        2.88800000e+03, 7.63000000e+02, 8.71700000e+03, 8.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 6.59000000e+02, 8.72000000e+02,
        3.30000000e+01, 5.56000000e+02, 6.99000000e+02, 1.31300000e+03,
        3.62000000e+02, 3.10000000e+02, 3.24000000e+02, 5.03000000e+02,
        2.66000000e+02, 2.80000000e+02, 6.49000000e+02, 2.10000000e+01,
        7.86000000e+02, 1.40000000e+02, 9.35000000e+02, 5.00800000e+03,
        2.13000000e+03, 9.59000000e+02, 3.92900000e+03, 1.08200000e+03,
        2.80900000e+03, 4.25000000e+02, 7.40000000e+01, 2.41400000e+03,
        5.50000000e+01, 5.83500000e+03, 1.41500000e+03, 1.28500000e+03,
        1.68700000e+03, 1.44800000e+03],
       [1.13000000e+02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.86800000e+03, 1.72300000e+03, 1.82400000e+03, 1.94700000e+03,
        2.19800000e+03, 2.23000000e+03, 2.66800000e+03, 2.76000000e+03,
        3.21400000e+03, 2.85500000e+03, 2.33500000e+03, 1.74900000e+03,
        1.63600000e+03, 1.79500000e+03, 1.34000000e+03, 8.24000000e+02,
        3.91712763e+01, 9.78000000e+02, 5.27200000e+03, 3.47500000e+03,
        2.82400000e+03, 2.40200000e+03, 5.70000000e+02, 1.04000000e+02,
        2.40000000e+01, 1.37000000e+02, 3.36000000e+02, 8.70800000e+03,
        5.27200000e+03, 8.55000000e+02, 1.52820000e+04, 1.40000000e+01,
        4.00000000e+00, 0.00000000e+00, 1.10400000e+03, 1.26400000e+03,
        2.60000000e+01, 1.04500000e+03, 1.74600000e+03, 2.42800000e+03,
        4.03000000e+02, 3.97000000e+02, 5.57000000e+02, 8.91000000e+02,
        5.61000000e+02, 3.95000000e+02, 1.00600000e+03, 2.10000000e+01,
        1.37300000e+03, 1.78000000e+02, 1.86900000e+03, 6.93800000e+03,
        3.06100000e+03, 1.75900000e+03, 5.05000000e+03, 2.10700000e+03,
        6.35100000e+03, 6.17000000e+02, 1.42000000e+02, 1.69600000e+03,
        9.40000000e+01, 1.24600000e+04, 1.27900000e+03, 2.87500000e+03,
        4.73200000e+03, 3.57400000e+03],
       [1.70000000e+02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.95400000e+03, 1.70600000e+03, 1.80400000e+03, 2.30800000e+03,
        3.37600000e+03, 3.91700000e+03, 3.85900000e+03, 3.66200000e+03,
        4.08200000e+03, 3.69400000e+03, 2.79900000e+03, 1.99500000e+03,
        1.82900000e+03, 1.87300000e+03, 1.54500000e+03, 1.13500000e+03,
        3.96887318e+01, 1.31700000e+03, 1.21620000e+04, 4.29600000e+03,
        2.98600000e+03, 2.34600000e+03, 5.83000000e+02, 1.13000000e+02,
        3.10000000e+01, 2.66000000e+02, 5.93000000e+02, 9.24900000e+03,
        1.21620000e+04, 1.31000000e+03, 1.95540000e+04, 2.10000000e+01,
        4.00000000e+00, 5.00000000e+00, 1.35100000e+03, 1.61200000e+03,
        5.60000000e+01, 1.61900000e+03, 1.52700000e+03, 2.92200000e+03,
        7.96000000e+02, 7.38000000e+02, 7.48000000e+02, 1.22000000e+03,
        6.93000000e+02, 4.30000000e+02, 1.14000000e+03, 3.70000000e+01,
        1.43700000e+03, 3.59000000e+02, 2.83900000e+03, 8.54700000e+03,
        3.50500000e+03, 2.05500000e+03, 6.29400000e+03, 6.39000000e+02,
        1.34110000e+04, 1.20500000e+03, 3.09000000e+02, 3.90800000e+03,
        1.19000000e+02, 1.78090000e+04, 4.67900000e+03, 5.83800000e+03,
        5.17600000e+03, 2.11600000e+03],
       [9.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.18000000e+02, 3.13000000e+02, 2.97000000e+02, 2.69000000e+02,
        2.53000000e+02, 2.09000000e+02, 2.63000000e+02, 4.03000000e+02,
        5.29000000e+02, 4.08000000e+02, 2.84000000e+02, 1.68000000e+02,
        1.69000000e+02, 2.16000000e+02, 2.00000000e+02, 1.56000000e+02,
        3.90434443e+01, 6.30000000e+01, 5.85000000e+02, 3.52000000e+02,
        3.62000000e+02, 3.05000000e+02, 1.41000000e+02, 1.80000000e+01,
        1.40000000e+01, 1.00000000e+01, 3.20000000e+01, 1.08000000e+03,
        5.85000000e+02, 1.14000000e+02, 2.02800000e+03, 1.20000000e+01,
        0.00000000e+00, 0.00000000e+00, 2.23000000e+02, 2.44000000e+02,
        5.00000000e+00, 7.30000000e+01, 2.17000000e+02, 3.35000000e+02,
        4.50000000e+01, 6.00000000e+01, 5.50000000e+01, 1.00000000e+02,
        7.60000000e+01, 3.70000000e+01, 1.50000000e+02, 4.00000000e+00,
        1.75000000e+02, 3.10000000e+01, 1.86000000e+02, 8.41000000e+02,
        3.46000000e+02, 2.17000000e+02, 1.06300000e+03, 0.00000000e+00,
        6.47000000e+02, 1.20000000e+01, 1.60000000e+01, 7.37000000e+02,
        8.00000000e+00, 9.89000000e+02, 3.21000000e+02, 3.27000000e+02,
        2.64000000e+02, 7.70000000e+01],
       [4.30000000e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.19000000e+02, 6.97000000e+02, 6.43000000e+02, 7.10000000e+02,
        6.35000000e+02, 6.87000000e+02, 8.54000000e+02, 9.31000000e+02,
        9.67000000e+02, 9.65000000e+02, 8.50000000e+02, 9.56000000e+02,
        1.17400000e+03, 1.35500000e+03, 9.09000000e+02, 6.05000000e+02,
        4.54060923e+01, 1.62100000e+03, 1.23800000e+03, 1.80400000e+03,
        1.37000000e+03, 9.28000000e+02, 2.29000000e+02, 3.20000000e+01,
        1.40000000e+01, 2.30000000e+01, 7.10000000e+01, 4.10800000e+03,
        1.23800000e+03, 5.98000000e+02, 5.93300000e+03, 7.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 2.50000000e+02, 4.88000000e+02,
        1.40000000e+01, 5.61000000e+02, 3.92000000e+02, 8.29000000e+02,
        3.27000000e+02, 1.80000000e+02, 3.72000000e+02, 3.44000000e+02,
        1.71000000e+02, 2.74000000e+02, 4.26000000e+02, 1.80000000e+01,
        5.87000000e+02, 1.22000000e+02, 5.71000000e+02, 4.37800000e+03,
        1.93800000e+03, 7.08000000e+02, 2.42300000e+03, 2.68800000e+03,
        3.03000000e+02, 9.00000000e+01, 2.80000000e+01, 3.80000000e+01,
        2.10000000e+01, 5.47200000e+03, 1.00000000e+00, 8.30000000e+02,
        8.20000000e+02, 3.82100000e+03]])

#数が多いので、分割して処理

In [7]:
corr = np.corrcoef([np_edo[:, 0], np_edo[:, 1], np_edo[:, 2], np_edo[:, 3], np_edo[:, 4], np_edo[:, 5], np_edo[:, 6], np_edo[:, 7], np_edo[:, 8], np_edo[:, 9],
                    np_edo[:, 10], np_edo[:, 11], np_edo[:, 12], np_edo[:, 13], np_edo[:, 14], np_edo[:, 15], np_edo[:, 16], np_edo[:, 17], np_edo[:, 18], np_edo[:, 19],
                    np_edo[:, 20], np_edo[:, 21], np_edo[:, 22], np_edo[:, 23], np_edo[:, 24], np_edo[:, 25], np_edo[:, 26], np_edo[:, 27], np_edo[:, 28], np_edo[:, 29],
                    np_edo[:, 30], np_edo[:, 31], np_edo[:, 32], np_edo[:, 33], np_edo[:, 34], np_edo[:, 35], np_edo[:, 36], np_edo[:, 37], np_edo[:, 38], np_edo[:, 39],
                    np_edo[:, 40], np_edo[:, 41], np_edo[:, 42], np_edo[:, 43], np_edo[:, 44], np_edo[:, 45], np_edo[:, 46], np_edo[:, 47], np_edo[:, 48], np_edo[:, 49],
                    np_edo[:, 50], np_edo[:, 51], np_edo[:, 52], np_edo[:, 53], np_edo[:, 54], np_edo[:, 55], np_edo[:, 56], np_edo[:, 57], np_edo[:, 58], np_edo[:, 59],
                    np_edo[:, 60], np_edo[:, 61], np_edo[:, 62], np_edo[:, 63], np_edo[:, 64], np_edo[:, 65], np_edo[:, 66], np_edo[:, 67], np_edo[:, 68], np_edo[:, 69]])

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\numpy\lib\function_base.py:2400: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\numpy\lib\function_base.py:2401: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]

In [8]:
corr[0,0:70]

array([ 1.        ,  0.27142652,  0.57436088,         nan,  0.87081959,
        0.84441771,  0.8279186 ,  0.86883672,  0.8828081 ,  0.89079001,
        0.89883874,  0.89875968,  0.88691005,  0.88662608,  0.89792559,
        0.88761663,  0.86060431,  0.83968549,  0.81473402,  0.7684758 ,
       -0.23624139,  0.78610933,  0.88881552,  0.89513673,  0.87858777,
        0.85511624,  0.80496526,  0.67104907,  0.63358012,  0.84506359,
        0.71992735,  0.88072551,  0.88881552,  0.79599529,  0.89947975,
        0.05344147,  0.46002118,  0.57033435,  0.79470346,  0.83641461,
        0.76349188,  0.90056884,  0.79827293,  0.89072432,  0.87166499,
        0.91419155,  0.89743021,  0.8839839 ,  0.89156398,  0.85632003,
        0.86945537,  0.67051024,  0.88610461,  0.62995707,  0.90156618,
        0.85925091,  0.87600215,  0.87956665,  0.83700061,  0.44307783,
        0.85866969,  0.77098323,  0.83277585,  0.54649212,  0.58660714,
        0.89028495,  0.7462845 ,  0.87348485,  0.80783275,  0.61080736])

In [9]:
pd_corr = pd.Series(corr[0].tolist())

In [10]:
pd_corr

0     1.000000
1     0.271427
2     0.574361
3          NaN
4     0.870820
5     0.844418
6     0.827919
7     0.868837
8     0.882808
9     0.890790
10    0.898839
11    0.898760
12    0.886910
13    0.886626
14    0.897926
15    0.887617
16    0.860604
17    0.839685
18    0.814734
19    0.768476
20   -0.236241
21    0.786109
22    0.888816
23    0.895137
24    0.878588
25    0.855116
26    0.804965
27    0.671049
28    0.633580
29    0.845064
        ...
40    0.763492
41    0.900569
42    0.798273
43    0.890724
44    0.871665
45    0.914192
46    0.897430
47    0.883984
48    0.891564
49    0.856320
50    0.869455
51    0.670510
52    0.886105
53    0.629957
54    0.901566
55    0.859251
56    0.876002
57    0.879567
58    0.837001
59    0.443078
60    0.858670
61    0.770983
62    0.832776
63    0.546492
64    0.586607
65    0.890285
66    0.746285
67    0.873485
68    0.807833
69    0.610807
Length: 70, dtype: float64

In [11]:
pd_corr.to_csv(r'C:\KGR5\edogawa_kaneda_corr.csv')