In [1]:
import pandas as pd
import numpy as np

In [2]:
edo = pd.read_csv(r'C:\KGR5\edogawa2017.csv', encoding = 'cp932')

In [3]:
edo[0:10]

      地区  自転車盗数  住民数(合計)  住民数(男性)  住民数(女性)  人口密度\n[人/k㎡]  面積[k㎡]    世帯数
0   東小松川     32    11383     5814     5569  10045.005290  1.1332   5479
1  西小松川町      3     3380     1764     1616   6452.844597  0.5238   1596
2    小松川     40    16293     7852     8441   9531.414531  1.7094   7003
3    西葛西    172    45320    22636    22684  22787.610620  1.9888  22369
4    中葛西    137    38262    20003    18259  23319.112630  1.6408  21215
5    北葛西     42    19816    10114     9702  11756.748740  1.6855   8997
6    南葛西    113    34164    17521    16643  22611.688400  1.5109  15217
7    東葛西    170    42692    22648    20044  15219.964350  2.8050  22872
8     新堀      9     4576     2409     2167  13298.459750  0.3441   1897
9    清新町     43    14339     6907     7432  14975.456920  0.9575   5988

In [4]:
edo_tmp = edo.drop('地区', axis=1)
#edo_tmp = edo_tmp.drop('Unnamed: 8', axis=1)
edo_tmp[0:10]

   自転車盗数  住民数(合計)  住民数(男性)  住民数(女性)  人口密度\n[人/k㎡]  面積[k㎡]    世帯数
0     32    11383     5814     5569  10045.005290  1.1332   5479
1      3     3380     1764     1616   6452.844597  0.5238   1596
2     40    16293     7852     8441   9531.414531  1.7094   7003
3    172    45320    22636    22684  22787.610620  1.9888  22369
4    137    38262    20003    18259  23319.112630  1.6408  21215
5     42    19816    10114     9702  11756.748740  1.6855   8997
6    113    34164    17521    16643  22611.688400  1.5109  15217
7    170    42692    22648    20044  15219.964350  2.8050  22872
8      9     4576     2409     2167  13298.459750  0.3441   1897
9     43    14339     6907     7432  14975.456920  0.9575   5988

In [5]:
np_edo = edo_tmp.values

In [6]:
np_edo[0:10]

array([[3.20000000e+01, 1.13830000e+04, 5.81400000e+03, 5.56900000e+03,
        1.00450053e+04, 1.13320000e+00, 5.47900000e+03],
       [3.00000000e+00, 3.38000000e+03, 1.76400000e+03, 1.61600000e+03,
        6.45284460e+03, 5.23800000e-01, 1.59600000e+03],
       [4.00000000e+01, 1.62930000e+04, 7.85200000e+03, 8.44100000e+03,
        9.53141453e+03, 1.70940000e+00, 7.00300000e+03],
       [1.72000000e+02, 4.53200000e+04, 2.26360000e+04, 2.26840000e+04,
        2.27876106e+04, 1.98880000e+00, 2.23690000e+04],
       [1.37000000e+02, 3.82620000e+04, 2.00030000e+04, 1.82590000e+04,
        2.33191126e+04, 1.64080000e+00, 2.12150000e+04],
       [4.20000000e+01, 1.98160000e+04, 1.01140000e+04, 9.70200000e+03,
        1.17567487e+04, 1.68550000e+00, 8.99700000e+03],
       [1.13000000e+02, 3.41640000e+04, 1.75210000e+04, 1.66430000e+04,
        2.26116884e+04, 1.51090000e+00, 1.52170000e+04],
       [1.70000000e+02, 4.26920000e+04, 2.26480000e+04, 2.00440000e+04,
        1.52199644e+04, 2.80500000e+00, 2.28720000e+04],
       [9.00000000e+00, 4.57600000e+03, 2.40900000e+03, 2.16700000e+03,
        1.32984597e+04, 3.44100000e-01, 1.89700000e+03],
       [4.30000000e+01, 1.43390000e+04, 6.90700000e+03, 7.43200000e+03,
        1.49754569e+04, 9.57500000e-01, 5.98800000e+03]])

In [7]:
np.corrcoef([np_edo[:, 0], np_edo[:, 1], np_edo[:, 2], np_edo[:, 3], np_edo[:, 4], np_edo[:, 5], np_edo[:, 6]])

array([[ 1.        ,  0.89700701,  0.89494894,  0.89770735,  0.36908108,
         0.69057537,  0.90621934],
       [ 0.89700701,  1.        ,  0.99924325,  0.99918883,  0.31972081,
         0.78894298,  0.99349495],
       [ 0.89494894,  0.99924325,  1.        ,  0.99686633,  0.31774171,
         0.78861189,  0.99452779],
       [ 0.89770735,  0.99918883,  0.99686633,  1.        ,  0.32125997,
         0.78802768,  0.99084137],
       [ 0.36908108,  0.31972081,  0.31774171,  0.32125997,  1.        ,
        -0.18407762,  0.3307733 ],
       [ 0.69057537,  0.78894298,  0.78861189,  0.78802768, -0.18407762,
         1.        ,  0.77428415],
       [ 0.90621934,  0.99349495,  0.99452779,  0.99084137,  0.3307733 ,
         0.77428415,  1.        ]])