In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [2]:
edo = pd.read_csv(r'C:\KGR5\edogawa2017+cluster.csv', encoding = 'cp932')

In [3]:
edo[0:10]

,#,地区,自転車盗数,住民数(合計),住民数(男性),住民数(女性),人口密度[人/k㎡],面積[k㎡],世帯数,クラスタ,...,男性30代,男性40代,男性50代,男性60以上,女性未成年,女性20代,女性30代,女性40代,女性50代,女性60以上
0,0,東小松川,32,11383,5814,5569,10045.005290,1.1332,5479,0,...,828,984,789,1477,1011,626,761,907,677,1682
1,1,西小松川町,3,3380,1764,1616,6452.844597,0.5238,1596,0,...,206,286,232,506,283,135,162,242,218,565
2,2,小松川,40,16293,7852,8441,9531.414531,1.7094,7003,0,...,861,1362,1214,1906,1593,796,920,1466,1204,2425
3,3,西葛西,172,45320,22636,22684,22787.610620,1.9888,22369,1,...,3751,3962,3023,4496,4261,2974,3585,3849,2714,5318
4,4,中葛西,137,38262,20003,18259,23319.112630,1.6408,21215,1,...,3534,3707,2664,3396,3133,3097,2980,3257,2119,3716
5,5,北葛西,42,19816,10114,9702,11756.748740,1.6855,8997,0,...,1348,1802,1454,2461,1897,981,1205,1657,1175,2792
6,6,南葛西,113,34164,17521,16643,22611.688400,1.5109,15217,1,...,2788,3189,2370,3273,3628,2154,2545,3006,2051,3606
7,7,東葛西,170,42692,22648,20044,15219.964350,2.8050,22872,1,...,3954,4176,3079,3910,3589,3363,3341,3551,2384,4125
8,8,新堀,9,4576,2409,2167,13298.459750,0.3441,1897,0,...,289,503,335,427,517,221,280,439,245,465
9,9,清新町,43,14339,6907,7432,14975.456920,0.9575,5988,0,...,937,981,804,2143,1291,614,943,999,944,2674

In [4]:
edo_ = edo.drop(edo.columns[0:9], axis=1)

In [5]:
edo_[0:10]

,クラスタ,男性未成年,男性20代,男性30代,男性40代,男性50代,男性60以上,女性未成年,女性20代,女性30代,女性40代,女性50代,女性60以上
0,0,1035,744,828,984,789,1477,1011,626,761,907,677,1682
1,0,294,238,206,286,232,506,283,135,162,242,218,565
2,0,1648,767,861,1362,1214,1906,1593,796,920,1466,1204,2425
3,1,4319,3117,3751,3962,3023,4496,4261,2974,3585,3849,2714,5318
4,1,3211,3541,3534,3707,2664,3396,3133,3097,2980,3257,2119,3716
5,0,1924,1114,1348,1802,1454,2461,1897,981,1205,1657,1175,2792
6,1,3727,2475,2788,3189,2370,3273,3628,2154,2545,3006,2051,3606
7,1,3890,4015,3954,4176,3079,3910,3589,3363,3341,3551,2384,4125
8,0,585,278,289,503,335,427,517,221,280,439,245,465
9,0,1359,708,937,981,804,2143,1291,614,943,999,944,2674

In [6]:
edo_np = edo_.values
edo_x = edo_np[:,1:12]
edo_y = edo_np[:,0]

In [7]:
edo_x[0:10]

array([[1035,  744,  828,  984,  789, 1477, 1011,  626,  761,  907,  677],
       [ 294,  238,  206,  286,  232,  506,  283,  135,  162,  242,  218],
       [1648,  767,  861, 1362, 1214, 1906, 1593,  796,  920, 1466, 1204],
       [4319, 3117, 3751, 3962, 3023, 4496, 4261, 2974, 3585, 3849, 2714],
       [3211, 3541, 3534, 3707, 2664, 3396, 3133, 3097, 2980, 3257, 2119],
       [1924, 1114, 1348, 1802, 1454, 2461, 1897,  981, 1205, 1657, 1175],
       [3727, 2475, 2788, 3189, 2370, 3273, 3628, 2154, 2545, 3006, 2051],
       [3890, 4015, 3954, 4176, 3079, 3910, 3589, 3363, 3341, 3551, 2384],
       [ 585,  278,  289,  503,  335,  427,  517,  221,  280,  439,  245],
       [1359,  708,  937,  981,  804, 2143, 1291,  614,  943,  999,  944]],
      dtype=int64)

In [8]:
edo_y[0:10]

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [9]:
sc = StandardScaler()
edo_std = sc.fit_transform(edo_x)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [10]:
edo_std[0:10]

array([[-3.74744332e-01, -2.94502581e-01, -3.04303056e-01,
        -3.97857244e-01, -3.72589818e-01, -2.81003222e-01,
        -3.65483575e-01, -3.79959939e-01, -3.17758253e-01,
        -3.97379594e-01, -3.85847879e-01],
       [-1.06550441e+00, -8.42501367e-01, -9.27622120e-01,
        -1.04015075e+00, -1.06253551e+00, -1.01082581e+00,
        -1.06667966e+00, -9.67467420e-01, -9.82164163e-01,
        -1.07260183e+00, -1.04724524e+00],
       [ 1.96694164e-01, -2.69593546e-01, -2.71233073e-01,
        -5.00249437e-02,  1.53849895e-01,  4.14415694e-02,
         1.95088022e-01, -1.76545944e-01, -1.41396750e-01,
         1.70213234e-01,  3.73534281e-01],
       [ 2.68659991e+00,  2.27546010e+00,  2.62489570e+00,
         2.34247236e+00,  2.39462505e+00,  1.98813623e+00,
         2.76485610e+00,  2.42954630e+00,  2.81459950e+00,
         2.58984420e+00,  2.54937311e+00],
       [ 1.65372250e+00,  2.73465276e+00,  2.40743551e+00,
         2.10782359e+00,  1.94993833e+00,  1.16135471e+00,
         1.67838744e+00,  2.57672231e+00,  2.14353844e+00,
         1.98874410e+00,  1.69200615e+00],
       [ 4.53981317e-01,  1.06207993e-01,  2.16799700e-01,
         3.54859216e-01,  4.51133497e-01,  4.58590425e-01,
         4.87895179e-01,  4.48163455e-02,  1.74722923e-01,
         3.64149245e-01,  3.31746648e-01],
       [ 2.13473761e+00,  1.58017311e+00,  1.65985348e+00,
         1.63116451e+00,  1.58576591e+00,  1.06890551e+00,
         2.15516225e+00,  1.44837291e+00,  1.66103999e+00,
         1.73388578e+00,  1.59402136e+00],
       [ 2.28668618e+00,  3.24799550e+00,  2.82832620e+00,
         2.53939329e+00,  2.46399122e+00,  1.54768717e+00,
         2.11759817e+00,  2.89500539e+00,  2.54395669e+00,
         2.28726341e+00,  2.07385866e+00],
       [-7.94234255e-01, -7.99181305e-01, -8.44446104e-01,
        -8.40469246e-01, -9.34951300e-01, -1.07020376e+00,
        -8.41295205e-01, -8.64563869e-01, -8.51279527e-01,
        -8.72573590e-01, -1.00833952e+00],
       [-7.27115867e-02, -3.33490637e-01, -1.95071901e-01,
        -4.00617818e-01, -3.54009593e-01,  2.19575405e-01,
        -9.57927721e-02, -3.94318574e-01, -1.15885338e-01,
        -3.03965390e-01, -1.11346358e-03]])

In [11]:
clf = LogisticRegression()
edo_clf = clf.fit(edo_std, edo_y)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [12]:
edo_clf.intercept_

array([-1.27877311])

In [13]:
edo_clf.coef_

array([[-0.17452996,  0.54363086,  0.60751945,  0.3794106 ,  0.06225519,
        -0.59182178, -0.04247961,  0.74912201,  0.78487469,  0.43953121,
        -0.06023375]])